apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-quarkus
  namespace: johannes-workshop
spec:
  paused: true
  selector:
    matchLabels:
      app: todo-api-quarkus
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-api-quarkus
    spec:
      containers:
        - name: todo-api-quarkus
          image: todo-api-quarkus
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: APP_STAGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-api-quarkus
                  key: app.stage-name
      serviceAccountName: todo-api-quarkus